version: '3'
services:
  pequeno_cesar:
    environment:
      - APP_MODE=dev
      - NEO4J_DB_PASSWORD
      - JWT_SECRET_KEY
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - neo4j
  redis:
    image: "redis:5.0.8-alpine3.11"
    ports:
      - "172.17.0.1:6379:6379"
  neo4j:
    image: "neo4j:3.3.9"
    ports:
      - "172.17.0.1:7474:7474"
      - "172.17.0.1:7687:7687"
    environment:
      - NEO4J_AUTH
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
  prometheus:
    # http://172.17.0.1:9090/graph
    image: "prom/prometheus:v2.17.2"
    ports:
      - "172.17.0.1:9090:9090"
  grafana:
    # user:admin, password:admin
    image: "grafana/grafana:6.7.3"
    ports:
      - "172.17.0.1:3000:3000"
