version: '3.8'
services:
  pequeno_cesar:
    environment:
      - APP_MODE=${APP_MODE:?err}
    secrets:
      - neo4j_db_user
      - neo4j_db_password
      - default_app_user_name
      - default_app_user_password
      - default_app_admin_name
      - default_app_admin_password
      - jwt_secret_key
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - neo4j
  redis:
    image: "redis:5.0.8-alpine3.11"
    ports:
      - "172.17.0.1:6379:6379"
  neo4j:
    # http://172.17.0.1:7474/browser
    image: "neo4j:3.3.9"
    ports:
      - "172.17.0.1:7474:7474"
      - "172.17.0.1:7687:7687"
    # TODO: Use secrets instead of NEO4J_AUTH env variable
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:?err}
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
  prometheus:
    # http://172.17.0.1:9090/graph
    image: "prom/prometheus:v2.17.2"
    ports:
      - "172.17.0.1:9090:9090"
    volumes:
    - "./prometheus:/etc/prometheus"
    depends_on:
      - pequeno_cesar
  grafana:
    # http://172.17.0.1:3000  ->  user:admin, password:admin
    image: "grafana/grafana:6.7.3"
    ports:
      - "172.17.0.1:3000:3000"
    depends_on:
      - pequeno_cesar

# Set file permissions to 440
secrets:
  neo4j_db_user:
    file: ~/neo4j_db_user.txt
  neo4j_db_password:
    file: ~/neo4j_db_password.txt
  default_app_user_name:
    file: ~/default_app_user_name.txt
  default_app_user_password:
    file: ~/default_app_user_password.txt
  default_app_admin_name:
    file: ~/default_app_admin_name.txt
  default_app_admin_password:
    file: ~/default_app_admin_password.txt
  jwt_secret_key:
    file: ~/jwt_secret_key.txt
