apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  uid: prometheus01
  url: http://172.17.0.1:9090
  basicAuth: false
  withCredentials: false
  isDefault: true
  version: 1
  editable: true
