{
 "title": "pequeno_cesar",
 "description": "pequeno_cesar metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pequeno_cesar_flask_requests_total",
   "type": "graph",
   "description": "rate each 5 mins",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pequeno_cesar_flask_requests_total[5m]) * 100",
     "legendFormat": "{{endpoint}} {{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "pequeno_cesar_neo4j_requests_total",
   "type": "graph",
   "description": "rate each 5 mins",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pequeno_cesar_neo4j_requests_total[5m]) * 100",
     "legendFormat": "{{method}} {{object}}"
    }
   ]
  },
  {
   "title": "pequeno_cesar_neo4j_request_latency_seconds_bucket",
   "type": "graph",
   "description": "neo4j latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pequeno_cesar_neo4j_request_latency_seconds_bucket[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "pequeno_cesar_flask_request_latency_seconds_bucket",
   "type": "graph",
   "description": "flask latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pequeno_cesar_flask_request_latency_seconds_bucket[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "pequeno_cesar_flask_requests_inprogress",
   "type": "gauge",
   "description": "pending requests",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "pequeno_cesar_flask_requests_inprogress"
    }
   ]
  },
  {
   "title": "pequeno_cesar_neo4j_requests_inprogress",
   "type": "gauge",
   "description": "pending transactions",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pequeno_cesar_neo4j_requests_inprogress"
    }
   ]
  }
 ]
}